---
- hosts: servers
  vars_files:
    - vars.yaml
  gather_facts: false
  become: yes

  tasks:
    #be sudo with ansible
    - name: be sudo with ansible
      shell: sudo su -

    #create new user with shell named gizem
    - name: create new user with shell named gizem
      user: name={{ username }} shell=/bin/bash state=present

    #add a line to a file with directory
    - name: add a line to a file with directory
      lineinfile: dest=/etc/sudoers state=present regexp="^%{{ username }} ALL=(ALL) NOPASSWD: ALL" line="%{{ username }} ALL=(ALL) NOPASSWD: ALL"

    #enter the password for the new user
    - name: enter the password for the new user
      shell: echo "{{ password }}" | passwd --stdin {{ username }}





